### PR TITLE
expose auto_unbox in .api_get_operations, closes #53

### LINKED ISSUE #53: auto_unbox = FALSE prevents proper translation of unparameterized request
Hi Martin, @mtmorgan 

This is more of a question because it is possible that the API I'm working with is poorly defined (see output).
The `auto_unbox` default is preventing a proper request: 

``` r
library(oncoKBData)
#> Loading required package: AnVIL
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
okb <- oncoKB(token = "12345-27834yioasdhfakdfjf")
okb$annotateCopyNumberAlterationsPostUsingPOST_1
#> annotateCopyNumberAlterationsPostUsingPOST_1 
#> annotateCopyNumberAlterationsPost 
#> Description:
#>   Annotate copy number alterations.
#> 
#> Parameters:
#>   body ()
#>     List of queries. Please see swagger.json for request body format.
okb$annotateCopyNumberAlterationsPostUsingPOST_1(
    list(
        list(
            copyNameAlterationType = "AMPLIFICATION",
            evidenceTypes = list("GENE_SUMMARY"),
            gene = list(entrezGeneId = 0, hugoSymbol = "string"),
            id = "string", referenceGenome = "GRCh37", tumorType = "string"
        )
    )
)
#> Response [https://www.oncokb.org/api/v1/annotate/copyNumberAlterations]
#>   Date: 2022-04-08 00:38
#>   Status: 400
#>   Content-Type: application/problem+json
#>   Size: 346 B
#> <BINARY BODY>
```

<sup>Created on 2022-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Should there be an option for these poorly defined APIs to turn `auto_unbox = TRUE` on?

https://github.com/Bioconductor/AnVIL/blob/dc76c27a9be5c118a8e3a0c56387d739c22e6ce7/R/api.R#L131

PS. To be able to run the above query, you'd need an auth token.

### PR DESCRIPTION
**Pull request by LiNk-NY**
Hi Martin, @mtmorgan 
As discussed in #53, this would keep the default at `FALSE`. 
Best,
Marcel

### CODE REVIEW

**Comment by mtmorgan** [comment]
Can you tell me how this works a little bit further up the call stack? I see that this would be called by `.api_get_operations()`, but this isn't exported by the package so the argument `auto_unbox=` can't be set?

**Comment by LiNk-NY** [comment]
Hi Martin, @mtmorgan 

I was thinking of implementing the argument in the class-specific method because it may only be needed for my specific class
but it could go in the Service method instead, if preferred.

```r
setMethod(
    "operations", "oncoKB",
    function(x, ..., .deprecated = FALSE)
{
    callNextMethod(
        x, .headers = .api_header(x), auto_unbox = TRUE, ..., .deprecated = .deprecated
    )
})
```

Of course, I'd have to update the operations generic to include `auto_unbox` as well. 
If that's ok, I can update the PR.

**Comment by mtmorgan** [comment]
I _think_ that
```
diff --git a/R/Services.R b/R/Services.R
index 94ce2ff..5b09e57 100644
--- a/R/Services.R
+++ b/R/Services.R
@@ -30,6 +30,10 @@ empty_object <- setNames(list(), character())
 #'     `operations,Service-method`, to the internal `get_operation()`
 #'     function.
 #'
+#' @param auto_unbox logical(1) If FALSE (default) do not
+#'     automatically 'unbox' R scalar values from JSON arrays to JSON
+#'     scalers.
+#'
 #' @param .deprecated optional logical(1) include deprecated operations?
 #'
 #' @export
@@ -43,8 +47,11 @@ setGeneric(
 #' @export
 setMethod(
     "operations", "Service",
-    function(x, ..., .deprecated = FALSE)
+    function(x, ..., auto_unbox = FALSE, .deprecated = FALSE)
 {
+    stopifnot(
+        .is_scalar_logical(auto_unbox)
+    )
     operations <- .api_get_operations(.api(x), ...)
     deprecated <- .operation_field(operations, "deprecated")
     keep <- .deprecated | !vapply(deprecated, isTRUE, logical(1))
```
is all that is required, and has the advantage of documenting the argument.

**Comment by LiNk-NY** [comment]
Thanks Martin, I've applied the diff and added a `@describeIn` tag to avoid the documentation mismatch.

**Comment by mtmorgan** [comment]
Thanks @LiNk-NY ; I undid the `@describedIn` because it seemed to introduce an incomplete documentation element (only operation,Services would be described) and didn't seem to provide additional information beyond the solution adopted? Happy to consider a separate pull request with more comprehensive documentation refactoring (but I wouldn't think of this as a high priority).

**Comment by LiNk-NY** [comment]
Thanks Martin! Your solution works better with the documentation structure.

**Pull request closed without merging**
