### PR TITLE
remove trimws for workspace names with leading space, closes #86

### LINKED ISSUE #86: Access error with a specific workspace
One of the public workspaces that I have READER access (`terracontest/TOSC19-idap`) can't be accessed with the `avworkflows` function. Can someone help me to resolve this issue? Thanks!

```
> all_workspaces <- AnVIL::avworkspaces()
> ind <- grep("terracontest", all_workspaces$namespace)
> all_workspaces[ind,]
# A tibble: 1 × 5
  name        lastModified createdBy              namespace    accessLevel
  <chr>       <date>       <chr>                  <chr>        <chr>      
1 TOSC19-idap 2021-07-15   kunaphas.kon@gmail.com terracontest READER     
> all_workflows <- AnVIL::avworkflows(namespace = all_workspaces$namespace[ind], name = all_workspaces$name[ind])
Error: 'avworkflows' failed:
  Not Found (HTTP 404).
  workspace terracontest/TOSC19-idap does not exist or you do not have permission to use it
```

### PR DESCRIPTION
**Pull request by LiNk-NY**
- no effect for trailing spaces

### CODE REVIEW

**Review by mtmorgan — APPROVED** [review]
I wonder why I did this quite intentional clean-up in the first place, but I don't see any comment in the original commit.

Maybe it would be worth-while to introduce something like
```
.avworkspaces_clean <-
    function(.data)
{
    .data |>
        select(
            name = .data$workspace.name,
            lastModified = .data$workspace.lastModified,
            createdBy = .data$workspace.createdBy,
            namespace = .data$workspace.namespace,
            accessLevel = .data$accessLevel
        ) |>
        mutate(
            name = trimws(.data$name),
            name = .data$name,
            lastModified = as.Date(.data$lastModified)
        ) |>
        arrange(
            .data$name,
            desc(.data$lastModified)
        )
    )
}
```
making it easy to write a unit test?

**Comment by LiNk-NY** [comment]
I've added a unit test without using `trimws()`. The leading spaces in `name` should be preserved.

**Comment by LiNk-NY** [comment]
@mtmorgan Can this be merged?

**Comment by mtmorgan** [comment]
yes

**Pull request merged**
